# Generated by Django 4.0.4 on 2022-06-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Hasan', max_length=255),
        ),
    ]
