# Generated by Django 4.0.4 on 2022-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('data_id', models.IntegerField()),
                ('type', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('result', models.CharField(max_length=55)),
                ('note', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
