# Generated by Django 4.0.4 on 2022-05-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
